"""Repository-development v1 contracts.

The package is an additive boundary for later WorkItem, executor, scheduler,
generation, and adapter lanes.  Importing it performs only model definition;
it does not access Git, Graph-OS, inventories, the filesystem, or a network.
"""

from .contracts import CONTRACT_NAME, CONTRACT_VERSION, ContractVersion
from .contracts.schema import contract_schema_bundle
from .enums import (
    C10_FAILURE_CODES,
    BuildOutcome,
    CandidateState,
    EvidenceOutcome,
    ExecutionOutcome,
    FailureClass,
    GenerationState,
    JobState,
    LandingOutcome,
    LaneState,
    OperationKind,
    RefusalCode,
    ReleasePlanState,
    ReservationState,
    TargetKind,
    ValidationStage,
)
from .models import (
    AbsolutePath,
    ArtifactReference,
    BuildKey,
    BuildResult,
    Candidate,
    CandidateVersion,
    CapacitySnapshot,
    ConsentPolicy,
    ContractModel,
    DependencyEdge,
    DevelopmentRequest,
    ExecutionCommand,
    ExecutionResult,
    FloorRewrite,
    Generation,
    GitRef,
    GitSha,
    JobId,
    LaneReference,
    LeaseRecord,
    LogReference,
    OpaqueId,
    RelativePath,
    RepositoryIdentity,
    RepositoryJobResult,
    ResourceRequest,
    ResourceReservation,
    TargetPolicy,
    UtcDateTime,
    ValidationEvidence,
    ValidationPolicy,
    WorkItemId,
    WorkspaceProject,
    WorkspaceReleasePlan,
)
from .serialization import (
    canonical_digest,
    canonical_json,
    canonicalize,
    contract_schema,
    deserialize_contract,
    serialize_contract,
)
from .transitions import is_legal_transition, require_legal_transition

__all__ = [
    "AbsolutePath",
    "ArtifactReference",
    "BuildKey",
    "BuildOutcome",
    "BuildResult",
    "C10_FAILURE_CODES",
    "CONTRACT_NAME",
    "CONTRACT_VERSION",
    "Candidate",
    "CandidateState",
    "CandidateVersion",
    "CapacitySnapshot",
    "ConsentPolicy",
    "ContractModel",
    "ContractVersion",
    "DependencyEdge",
    "DevelopmentRequest",
    "EvidenceOutcome",
    "ExecutionCommand",
    "ExecutionOutcome",
    "ExecutionResult",
    "FloorRewrite",
    "FailureClass",
    "Generation",
    "GenerationState",
    "GitRef",
    "GitSha",
    "JobId",
    "JobState",
    "LandingOutcome",
    "LaneReference",
    "LaneState",
    "LeaseRecord",
    "LogReference",
    "OpaqueId",
    "OperationKind",
    "RefusalCode",
    "ReleasePlanState",
    "RelativePath",
    "RepositoryIdentity",
    "RepositoryJobResult",
    "ResourceRequest",
    "ResourceReservation",
    "ReservationState",
    "TargetKind",
    "TargetPolicy",
    "UtcDateTime",
    "ValidationEvidence",
    "ValidationPolicy",
    "ValidationStage",
    "WorkItemId",
    "WorkspaceProject",
    "WorkspaceReleasePlan",
    "canonical_digest",
    "canonical_json",
    "canonicalize",
    "contract_schema",
    "contract_schema_bundle",
    "deserialize_contract",
    "is_legal_transition",
    "require_legal_transition",
    "serialize_contract",
]
